### PR TITLE
Tag and Probe documentation update (gh-pages)

### PR DESCRIPTION
**Pull request by allanjales**
Visual update on documentation. On this Pull Request, [this merge](https://github.com/cernopendata/cms-opendata-guide/pull/68) is compiled.

### CODE REVIEW

**Comment by mvidalgarcia** [comment]
Oh wow.

image

**Comment by allanjales** [comment]
> Oh wow.
> 
> image

The gh-page branch is created from main branch by simply typing `mkdocs gh-deploy`. What i changed is presented [in this merge](https://github.com/cernopendata/cms-opendata-guide/pull/68).

I just compiled the main branch using the code above and made a pull request.

**Comment by jieunyoo** [comment]
Hi. I'm not sure what you mean by a visual representation. Is this a new pull request that you want merged, or just documentation regarding your compilation?

**Comment by allanjales** [comment]
> Hi. I'm not sure what you mean by a visual representation. Is this a new pull request that you want merged, or just documentation regarding your compilation?

This commit is not necessary after all, since the guide is in a link outside github.

The `gh-pages` branch is only necessary if the guide was located on github.io domain. `gh-pages` is default branch in `mkdocs` which the main documentation is compiled in HTML, CSS and Js format (in other words, is the site is built).

Since is pointless to update this branch, I will close this commit.

Thanks for all support!

**Pull request closed without merging**
