### PR TITLE
Object pages (jet,el,photon) + uncert pages (btag,JEC/JER,lep)

### PR DESCRIPTION
**Pull request by sib37385**
Includes additions by @jrw46742, @sib37385, and @npervan.
@npervan ---
Updated:
- Egamma
- Jets
- MET
- Muons
- Tools
- mkdocs.yml
Created:
- Btaguncertainties
- Jetuncertainties
- Leptonuncertainties

@jrw46742 ---
Updated:
- Jets
- Jetuncertainties

@sib37385 ---
Updated:
Jets
Btaguncertainties

### CODE REVIEW

**Comment by caredg** [comment]
@jrw46742, @sib37385, @npervan, @jmhogan, I am sorry to have checked this only now.  I thought it would be just a matter of deleting some blank lines and such but these contributions are really in a raw state.  I checked the document style with the `./run-tests.sh --check-docstyle` command and there just too many things that are not properly written (I attach the output: [runtest.log](https://github.com/cernopendata/cms-opendata-guide/files/7480279/runtest.log)).
 
I checked the first file, i.e., `docs/analysis/selection/objects/egamma.md`.  I noticed a few things that need a more careful consideration:
 
 * The documents do not really follow the markdown syntax.  [Here](https://www.markdownguide.org/tools/mkdocs/) one can find a quick reference for the elements that can be used.
 * One can also check a file with already good syntax, for instance [this one] (https://raw.githubusercontent.com/cernopendata/cms-opendata-guide/eedc8d880729c3ef69ea75c1ea38efa6216a1537/docs/analysis/selection/objects.md)  Note how the c++ is encapsulated
 * In the file in questions, there is a massive dump of code (and apparently a copy paste from the twiki page) which is not very instructive.  This is not the [spirit](https://github.com/cernopendata/cms-opendata-guide#the-guides-philosophy) of the guide as it will be very difficult (if not impossible) to understand for an external user.

I know the instructions on how to setup the local testing of the page can be improved and they perhaps lack many details of what we expect.  I will try to improve them and will appreciate your help in making them better.

Could you guys please take a look at this.  Maybe even a regular mkdown rendering site (or tool) could be used to improve the input.

Thanks a lot!

**Comment by npervan** [comment]
Hi @caredg--that is not the final version of the egamma page. I think this pull request was made before it was finished because we were combining pages written by multiple people. I will submit a separate pull request for that page but I think the formatting for the rest should be okay.

**Comment by katilp** [comment]
@npervan @caredg  any news on this PR? I would need to add some updates to these pages because of the 2015 release (mainly 2015 placeholders and links to the existing MiniAOD documentation). That would need to happen in the time scale of 2 weeks, and I need to understand where to put them. If I add anything to the current version it would likely be a mess to sort that out afterwards.

**Comment by jieunyoo** [comment]
This pull request has multiple formatting/build issues. It will be merged and then formatting fixed.

**Pull request merged**
