### PR TITLE
First 2024 updates: new page, mathjax

### PR DESCRIPTION
**Pull request by jmhogan**
Beginning work on #113 

Added MathJax to the mkdocs so that we can do latex formatting, and tweaked the navigation slightly. 
Added content for background modelling.

### CODE REVIEW

**Comment by jmhogan** [comment]
Leaving this PR open for a couple days, will add a few more new-content pages soon.

**Comment by jmhogan** [comment]
@katilp @caredg do you know anything about this link check? I don't know what's wrong with the 4th link in stats.md. And it seems like another link in a file I didn't touch now has a ? status on one link.... internet searching isn't pulling up anything helpful for diagnosing this.

**Comment by katilp** [comment]
It might be something intermittent, e.g. time-out for some reason. Rerunning the workflow could help.

**Comment by jmhogan** [comment]
Thanks @katilp I ended up replacing the links to two of the articles with different URLs. 

For my own reference later, rather than installing Ruby for myself I used the docker container in this README to test a file: https://github.com/dkhamsing/awesome_bot
(for cygwin, 'c:/cygwin64/home/...etc...':/mnt:ro instead of $PWD)

**Pull request merged**
