### PR TITLE
ci: added github actions workflow

### PR DESCRIPTION
**Pull request by audrium**
Here is an example of GH actions workflow run: https://github.com/audrium/cms-opendata-guide/actions/runs/366168186

### CODE REVIEW

**Comment by audrium** [comment]
I had to remove `mkdocs-awesome-pages-plugin` from `mkdocs.yml` to make it work. Plugin was not used since the docs structure is configured in `mkdocs.yml`. Because of that plugin was failing while building the docs (see error [here](https://github.com/audrium/cms-opendata-guide/runs/1395522080?check_suite_focus=true)).

**Review by ParthS007 — APPROVED** [review]
LGTM

**Comment by tiborsimko** [comment]
> I had to remove `mkdocs-awesome-pages-plugin` from `mkdocs.yml` to make it work. Plugin was not used since the docs structure is configured in `mkdocs.yml`. Because of that plugin was failing while building the docs (see error [here](https://github.com/audrium/cms-opendata-guide/runs/1395522080?check_suite_focus=true)).

`mkdocs-awesome-pages-plugin` is used here:

```console
$ git grep -C 2 awesome-pages mkdocs.yml
mkdocs.yml-82-plugins:
mkdocs.yml-83-  - search
mkdocs.yml:84:  - awesome-pages:
mkdocs.yml-85-      collapse_single_pages: false
```

and it is installed from `requirements.txt`. So dunno about removing it? BTW we are using it also for `docs.reana.io`...

Probably we should rather look at fixing `docs/.pages`?

**Comment by audrium** [comment]
These are the lines which I removed (that's what I meant by removing the plugin) to make it work. It does the same job as manually specifying `navigation structure` in `mkdocs.yml`. So if we want to align with `docs.reana.io` we probably need to delete that structure from `mkdocs.yml` and use the plugin instead.

According to the plugin docs:
`The awesome-pages plugin allows you to customize how your pages show up the navigation of your MkDocs without having to configure the full structure in your mkdocs.yml`

**Comment by audrium** [comment]
Removed `docs/.pages` to fix the navigation structure collision between `mkdocs.yml` and the plugin

**Pull request merged**
